cgo: Save encrypted wallet seed.
itswisdomagain/libwallet pull request #10
Opened 2024-01-30 09:05 UTC by JoeGruffins

I think solves some TODOs. Need to keep the seed around it seems in case the wallet closes at an inopportune time, before the user has seen it.

2024-02-13 11:17 UTC, itswisdomagain requested changes

2024-02-13 11:17 UTC, itswisdomagain commented on asset/walletbase.go
> +}
Can we move these to a `walletdata.go` file? Looks good otherwise!

2024-02-14 02:44 UTC, JoeGruffins commented
Moved to a new file https://github.com/itswisdomagain/libwallet/compare/c9cb1d40eb53f5ea8a0b47c34b6965dfdd66b6e6..1f2f3d4d43ce22e589f1006469b018ab486e29fe

2024-02-16 07:08 UTC, itswisdomagain requested changes

2024-02-16 07:08 UTC, itswisdomagain commented on asset/walletbase.go
> +	}
I'm thinking `saveWalletData` should do this if check, because it would ultimately be used to save other wallet info even if there is no encrypted seed to save.

2024-02-16 07:08 UTC, itswisdomagain commented on asset/walletdata.go
> +	}
Does this error for file not found? I don't think it should as watchonly wallets may not have the json file since nothing was saved for them.

2024-02-16 07:08 UTC, itswisdomagain commented on asset/walletbase.go
>  	}
A watch-only wallet will not have an encrypted seed. Does this account for that?

2024-02-19 06:17 UTC, JoeGruffins commented on asset/walletbase.go
> +	}
Maybe it can just save anyhow. Removing the check.

2024-02-19 07:06 UTC, JoeGruffins commented on asset/walletdata.go
> +	}
Oh yeah it would. Just returning an empty *walletData if file not found now.

2024-02-19 08:09 UTC, JoeGruffins commented on asset/walletbase.go
>  	}
No I wasn't thinking about it, but This is fine with and empty string "".

2024-02-19 08:12 UTC, JoeGruffins commented
Saving the file even if no ecrypted seed. Returning an empty struct if not file found. Using os instead of io/ioutil because I think it is deprecated. https://github.com/itswisdomagain/libwallet/compare/adba4eb70476e58ba4cf051b2f3a7f28354ebb14..bbd43882a71b006a269f96713e467f5ae668d83d

2024-03-05 12:25 UTC, itswisdomagain approved these changes

2024-03-05 12:25 UTC, merged