cgo: Add sign send transaction.
itswisdomagain/libwallet pull request #12
Opened 2024-02-02 13:50 UTC by JoeGruffins

closes #11 

Depends on all the other stuff atm.

2024-02-13 11:30 UTC, itswisdomagain requested changes

2024-02-13 11:30 UTC, itswisdomagain commented on asset/dcr/transactions.go
> +func (w *Wallet) SignSendTransaction(ctx context.Context, outputs []*Output, feeRate uint64) (signedTx []byte, txid *chainhash.Hash, fee uint64, err error) {
My understanding is that this method is supposed to create a signed tx that auto selects inputs to send funds to the specified outputs. I think it can be less complex if we follow the pattern in the [dcrwallet jsonrpc fundRawTransaction method](https://github.com/decred/dcrwallet/blob/bbb072e15a00b204c98f4feff7561d3ee3ea8550/internal/rpc/jsonrpc/methods.go#L862).

Basically, we just need to call `w.NewUnsignedTransaction`.

2024-02-13 11:31 UTC, itswisdomagain commented on asset/dcr/transactions.go
> +func (w *Wallet) SignSendTransaction(ctx context.Context, outputs []*Output, feeRate uint64) (signedTx []byte, txid *chainhash.Hash, fee uint64, err error) {
Also, the method name is a little complex / confusing. `CreateSignedTransaction`?

2024-02-14 03:40 UTC, JoeGruffins commented on asset/dcr/transactions.go
> +func (w *Wallet) SignSendTransaction(ctx context.Context, outputs []*Output, feeRate uint64) (signedTx []byte, txid *chainhash.Hash, fee uint64, err error) {
I think we will want to give an option to select inputs in this first iteration, so we will need the complexity anyhow. Let me double check.

2024-02-14 04:18 UTC, JoeGruffins commented
SignSendTransaction -> CreateSignedTransaction https://github.com/itswisdomagain/libwallet/compare/fc33133e2f1db779c6f74deaecc323225d4695cc..57c6fce16722b9f42c51e915691184a3a12119ec

2024-02-15 10:32 UTC, JoeGruffins commented
Greatly simplified and able to pick inputs https://github.com/itswisdomagain/libwallet/compare/793fe5ef8597787a6da7e9882b3efea9b6823f4b..ca1b6ac9907942e187aacc7260af4aae51085511

2024-02-16 07:49 UTC, JoeGruffins commented
Sorry changing once more. We can also have frozen utxo.

2024-02-16 16:02 UTC, JoeGruffins commented
Now we can specify inputs to ignore as well. Looks messy again. Lightly tested.

2024-02-21 12:05 UTC, JoeGruffins commented
Also marking change transactions https://github.com/itswisdomagain/libwallet/compare/53cb147625ef6819b677d15c628999f2bef9236f..da904280ab64b5a13d2df52ef8b32335c17810ba

2024-02-21 12:06 UTC, JoeGruffins commented on cgo/types.go
> +}
I should change these struct names too.

2024-03-05 12:55 UTC, itswisdomagain requested changes

2024-03-05 12:55 UTC, itswisdomagain commented on asset/dcr/transactions.go
> +	tx := baseTx.Copy()
I've forgotten why it is necessary to use a copy. Can you add a comment?

2024-03-05 12:55 UTC, itswisdomagain commented on asset/dcr/transactions.go
> +		ignoreCoinIDs[fmt.Sprintf("%s:%d", in.TxID, in.Vout)] = struct{}{}
nit: can have a `input.String()` method

2024-03-06 04:49 UTC, JoeGruffins commented on cgo/types.go
> +}
Changed.

2024-03-06 04:49 UTC, JoeGruffins commented on asset/dcr/transactions.go
> +		ignoreCoinIDs[fmt.Sprintf("%s:%d", in.TxID, in.Vout)] = struct{}{}
Added for the input type.

2024-03-06 05:46 UTC, JoeGruffins commented on asset/dcr/transactions.go
> +// closing the wallet directly after sending.
I tested some more today and the wallet will send the tx again on the next start up. Because we don't have access to a dcrd with this info stored I don't think we can know if it made it out onto the network unless we wait for a confirmation. So... no I think its fine. There's nothing we can know for certain without waiting too long.

2024-03-06 05:47 UTC, JoeGruffins commented on asset/dcr/transactions.go
> +// closing the wallet directly after sending.
I'm going to remove the note.

2024-03-06 05:51 UTC, JoeGruffins commented on asset/dcr/transactions.go
> +	tx := baseTx.Copy()
I think it's to remove any redeem scripts that might be already allocated. Let me check...

2024-03-06 05:59 UTC, JoeGruffins commented on asset/dcr/transactions.go
> +	tx := baseTx.Copy()
No it copies the witness data.

2024-03-06 06:01 UTC, JoeGruffins commented on asset/dcr/transactions.go
> +	tx := baseTx.Copy()
I guess to avoid altering the passed tx.

2024-03-06 06:03 UTC, JoeGruffins commented on asset/dcr/transactions.go
> +	tx := baseTx.Copy()
Added `// Copy the passed transaction to avoid altering it.` although its probably fine to alter it... I'd rather not mess with it since this is what we have been doing in dex.

2024-03-06 06:06 UTC, JoeGruffins commented
Adjusting comments mostly https://github.com/itswisdomagain/libwallet/compare/7fd8bab08247f0fa387b44fa072dc4b47145e7c5..dbec4ccb69244e9a73ab7562188d5fb951d6b6e5

2024-03-07 06:48 UTC, itswisdomagain requested changes

2024-03-07 06:48 UTC, itswisdomagain commented on asset/dcr/transactions.go
> +func (w *Wallet) signRawTransaction(ctx context.Context, baseTx *wire.MsgTx) (*wire.MsgTx, error) {
```suggestion
// signRawTransaction signs the provided transaction.
func (w *Wallet) signRawTransaction(ctx context.Context, baseTx *wire.MsgTx) (*wire.MsgTx, error) {
```

2024-03-07 06:48 UTC, itswisdomagain commented on asset/dcr/transactions.go
> +		}
The other inputSource doesn't call addUTXO. It adds the utxos early on and simply returns details. Not sure which is better, they're likely the same thing but it'd aid consistency if both do the same thing. I'm leaning towards preparing the details outside of the inputSource fn. And that makes me wonder if it is possible to have a different fn prepare and return the details, so this one is less congested.

2024-03-07 06:48 UTC, itswisdomagain commented on go.mod
> +	decred.org/dcrdex v0.6.3 // indirect
Looks like `go mod tidy` is needed.

2024-03-07 06:48 UTC, itswisdomagain commented on cgo/transactions.go
> +	}
out => in?

2024-03-07 06:48 UTC, itswisdomagain commented on cgo/transactions.go
> +	res, err := w.MainWallet().ListUnspent(ctx, 1, 9999999, nil, "default")
You did `math.MaxInt32` elsewhere.

2024-03-07 07:00 UTC, JoeGruffins commented on cgo/transactions.go
> +	res, err := w.MainWallet().ListUnspent(ctx, 1, 9999999, nil, "default")
Did I? This is what the dcrctl help said the value was.

2024-03-07 07:03 UTC, itswisdomagain commented on cgo/transactions.go
> +	res, err := w.MainWallet().ListUnspent(ctx, 1, 9999999, nil, "default")
In `wallet.CreateSignedTransaction`.

2024-03-07 07:26 UTC, JoeGruffins commented on asset/dcr/transactions.go
> +func (w *Wallet) signRawTransaction(ctx context.Context, baseTx *wire.MsgTx) (*wire.MsgTx, error) {
Fixed.

2024-03-07 07:49 UTC, JoeGruffins commented on asset/dcr/transactions.go
> +		}
I think I put it inside so that that we don't need to worry about calculating the fee. We can use the amount the dcrwallet calculates.

2024-03-07 07:59 UTC, JoeGruffins commented on asset/dcr/transactions.go
> +		}
Added a couple comments.

2024-03-07 08:02 UTC, JoeGruffins commented on go.mod
> +	decred.org/dcrdex v0.6.3 // indirect
Did this.

2024-03-07 08:04 UTC, JoeGruffins commented on cgo/transactions.go
> +	}
Yeah thanks, changed these two.

2024-03-07 08:13 UTC, JoeGruffins commented
go mod tidy and some comments https://github.com/itswisdomagain/libwallet/compare/dbec4ccb69244e9a73ab7562188d5fb951d6b6e5..33a2e58d3184f4b3b0e19e03a25e592f987654ee

2024-03-08 01:30 UTC, JoeGruffins commented on asset/dcr/transactions.go
> +		}
I guess it wouldn't be much work to estimate the fee, if you think we should. We could just copy whatever wallet is doing to make sure the amounts aren't different.

2024-03-27 22:09 UTC, itswisdomagain approved these changes

2024-03-27 22:09 UTC, merged