cgo: Return JSON payloads.
itswisdomagain/libwallet pull request #6
Opened 2023-12-25 07:21 UTC by JoeGruffins

This is on top of #2

All returns are a *C.char but they are json so that the consumer can determine if an error occured.

2024-01-02 16:57 UTC, itswisdomagain requested changes

2024-01-02 16:57 UTC, itswisdomagain commented on cgo/types.go
> +	Error     string `json:"error,omitempty"`
Can `Payload` be `any` and `Error`, `error`? Since the entire struct will be later marshalled to json, I think no need to marshal the payload before passing into this struct.

2024-01-02 16:57 UTC, itswisdomagain commented on cgo/types.go
> +	Error     string `json:"error,omitempty"`
Also, I'm thinking naming the type `CResponse` will make it more intuitive to know its intended use.

2024-01-03 05:46 UTC, JoeGruffins commented on cgo/types.go
> +	Error     string `json:"error,omitempty"`
Changed Msg -> CResponse. I am not sure about the types. I thought it was important the Payload is always a concrete type. Doesn't that make it simpler for the consumer? One function can break down the initial message and parse out the possible error, then individual functions can do what they want with the string payload. If it is any, it would need to be parsed differently based on the route would it not? I mean the initial Msg, sure the payload will need to be parsed differently anyhow, but the consumer will always have a string representation of whatever it is.

2024-01-03 05:49 UTC, JoeGruffins commented
Msg -> CResponse https://github.com/itswisdomagain/libwallet/compare/d5e698e8e096b927ff84c71d0d8f864aa19ccfc5..4b9ef825ce2354d579866c21e1c9a1ce9d96c7a2

2024-01-17 05:21 UTC, itswisdomagain requested changes
Looks good to go. Just a few thoughts.

2024-01-17 05:21 UTC, itswisdomagain commented on cgo/addresses.go
> +		return errCResponse("wallet with name %s no loaded", goString(walletName))
```suggestion
		return errCResponse("wallet with name %q is not loaded", goString(walletName))
```

2024-01-17 05:21 UTC, itswisdomagain commented on cgo/addresses.go
> +		return errCResponse("wallet with name %s no loaded", goString(walletName))
quoting the name will make the final message easier to understand if the name is multi-word.

2024-01-17 05:21 UTC, itswisdomagain commented on cgo/cgo.go
> +	return resCResponse("libwallet cgo initialized")
How about `errCResponse` and `successCResponse`? They're both responses at the end of the day, so `resCResponse` makes it seem this is more of a response than the other.

2024-01-17 05:21 UTC, itswisdomagain commented on cgo/types.go
> +// errCResponseWithCode will return an error to the consumer, and log it if possible.
same comment as the previous method

2024-01-17 05:21 UTC, itswisdomagain commented on cgo/types.go
> +	}
This log temporary? I can understand logging errors but if we log all returns, that would be quite some logs.

2024-01-17 05:21 UTC, itswisdomagain commented on cgo/walletloader.go
> +	return resCResponse(fmt.Sprintf("wallet %s loaded", name))
use %q?

2024-01-17 05:21 UTC, itswisdomagain commented on cgo/walletloader.go
> +		return errCResponse("wallet not loaded")
Saw another error of this nature, it includes the wallet name. Can we harmonize?

2024-01-17 06:19 UTC, JoeGruffins commented on cgo/addresses.go
> +		return errCResponse("wallet with name %s no loaded", goString(walletName))
changed to q

2024-01-17 06:20 UTC, JoeGruffins commented on cgo/cgo.go
> +	return resCResponse("libwallet cgo initialized")
ok.

2024-01-17 06:22 UTC, JoeGruffins commented on cgo/types.go
> +// errCResponseWithCode will return an error to the consumer, and log it if possible.
Changed with a sed.

2024-01-17 06:22 UTC, JoeGruffins commented on cgo/types.go
> +	}
I rather like it. What if I make it trace?

2024-01-17 06:24 UTC, JoeGruffins commented on cgo/walletloader.go
> +	return resCResponse(fmt.Sprintf("wallet %s loaded", name))
Changed to q.

2024-01-17 06:24 UTC, JoeGruffins commented on cgo/types.go
> +	}
Changed to trace...

2024-01-17 06:42 UTC, JoeGruffins commented
last review, if trace for that log is alright https://github.com/itswisdomagain/libwallet/compare/4b9ef825ce2354d579866c21e1c9a1ce9d96c7a2..a167ae6293d26a14bd67798a883cc6b9bab3e2c3

2024-01-17 13:21 UTC, itswisdomagain requested changes

2024-01-17 13:21 UTC, itswisdomagain commented on cgo/cgo.go
> +			errCResponse("close wallet error: %v", err)
Do you mean to return this here?

2024-01-17 13:21 UTC, itswisdomagain commented on cgo/walletloader.go
> +		return successCResponse(emptyJsonObject)
Shouldn't this error? Just taking another look now...

2024-01-18 02:09 UTC, JoeGruffins commented on cgo/cgo.go
> +			errCResponse("close wallet error: %v", err)
Oh wow, idk. what do we do here. We want to go through all of them. Do we want to return an error if one errors or just log? I don't think cake can support multiple wallets so maybe not a problem if we return err on any error...

2024-01-18 02:10 UTC, JoeGruffins commented on cgo/cgo.go
> +			errCResponse("close wallet error: %v", err)
Can it support multiple?

2024-01-18 02:23 UTC, JoeGruffins commented
ah bad rebase, one sec

2024-01-18 02:26 UTC, JoeGruffins commented
Reverted to the obvious log. We dont want to return if there is another wallet to close, but we probably do want to error in the end. Unsure if we need to handle it differently atm so just reverting. Also erroring if no wallet. https://github.com/itswisdomagain/libwallet/compare/a167ae6293d26a14bd67798a883cc6b9bab3e2c3..164a9c508a9bf031de575a5e4d6b2dd347ac937e

2024-01-24 10:09 UTC, itswisdomagain commented on cgo/cgo.go
> +			errCResponse("close wallet error: %v", err)
Yes, it can, I believe.

2024-01-24 12:12 UTC, merged