Sync
itswisdomagain/libwallet pull request #7
Opened 2023-12-26 12:27 UTC by JoeGruffins

depends on #2 and #6

closes #5

2023-12-26 12:29 UTC, JoeGruffins commented on cgo/cgo.go
> +	_, bestHeight := w.MainChainTip(ctx)
This isn't correct. How do we know the highest known block among peers?

2024-01-02 17:08 UTC, itswisdomagain requested changes

2024-01-02 17:08 UTC, itswisdomagain commented on cgo/cgo.go
> +	if err := json.Unmarshal([]byte(peersJSON), &peers); err != nil {
Can be a comma separated string, so you don't need to do json marhsalling / unmarshalling.

2024-01-02 17:08 UTC, itswisdomagain commented on cgo/cgo.go
> +			log.Infof("Disconnected to peer at %s. %d total peers.", addr, peerCount)
Disconnected from

2024-01-02 17:08 UTC, itswisdomagain commented on cgo/cgo.go
> +	_, bestHeight := w.MainChainTip(ctx)
`w.syncer.EstimateMainChainTip()`, but that should be in `asset/dcr` because `w.syncer` is a private variable.

Or alternatively...
```
n,_ := w.NetworkBackend()
n.(*spv.Syncer).EstimateMainChainTip()
```

2024-01-02 17:08 UTC, itswisdomagain commented on cgo/cgo.go
> +		BestHeight:     int(bestHeight),
BestHeight usually means the wallet's best height? Maybe `TargetHeight`?

2024-01-03 06:46 UTC, JoeGruffins commented on cgo/cgo.go
> +	_, bestHeight := w.MainChainTip(ctx)
Thanks that works great!

2024-01-03 06:50 UTC, JoeGruffins commented on cgo/cgo.go
> +	if err := json.Unmarshal([]byte(peersJSON), &peers); err != nil {
Is marshalling/unmarshalling expensive? Would still need to parse into a string slice to use `peers...` later.

2024-01-03 06:51 UTC, JoeGruffins commented on cgo/cgo.go
> +			log.Infof("Disconnected to peer at %s. %d total peers.", addr, peerCount)
Fixed.

2024-01-03 06:55 UTC, JoeGruffins commented on cgo/cgo.go
> +		BestHeight:     int(bestHeight),
Changed.

2024-01-03 06:56 UTC, JoeGruffins commented
bestheight -> targetheight https://github.com/itswisdomagain/libwallet/compare/db9ec162792403c80de98b9cc4a1e596f79e3a6a..9215d392e15949fb4013d2f2d402d597bbef348a

2024-01-03 07:31 UTC, JoeGruffins commented
use peers with commas https://github.com/itswisdomagain/libwallet/compare/9215d392e15949fb4013d2f2d402d597bbef348a..55c8a6205ed7298945ea1945cbb3a8ededf3c2a1

2024-01-15 07:00 UTC, JoeGruffins commented
Added the first error code https://github.com/itswisdomagain/libwallet/compare/55c8a6205ed7298945ea1945cbb3a8ededf3c2a1..eb72b60ff69aa030677a8f5bb16ff60b2ef1fd08

2024-01-16 07:31 UTC, JoeGruffins commented
added numpeers https://github.com/itswisdomagain/libwallet/compare/eb72b60ff69aa030677a8f5bb16ff60b2ef1fd08..94575c4f29b79e228185d72f7d1e1a5a2d06fa8b

2024-01-24 10:24 UTC, itswisdomagain requested changes

2024-01-24 10:24 UTC, itswisdomagain commented on cgo/cgo.go
> +			log.Info("Sync completed.")
I think `log` in the callbacks need to use the mtx and check for nil. It's theoretically possible for the logger to be closed while sync is ongoing, right?

2024-01-24 10:24 UTC, itswisdomagain commented on cgo/cgo.go
> +			log.Info("Sync completed.")
Can make a `logInfo` fn that does the mtx locking and nil log check.

2024-01-24 10:24 UTC, itswisdomagain commented on cgo/cgo.go
> +func syncWallet(cName, cPeers *C.char) *C.char {
Maybe move this and the other sync fn to a `sync.go` file?

2024-01-24 10:24 UTC, itswisdomagain commented on cgo/types.go
> +	// iota not for error code readability.
Don't understand this.

2024-01-24 12:07 UTC, JoeGruffins commented on cgo/cgo.go
> +			log.Info("Sync completed.")
I changed to the wallet logs. Are those fine?.

2024-01-24 12:07 UTC, JoeGruffins commented on cgo/cgo.go
> +func syncWallet(cName, cPeers *C.char) *C.char {
moved to a new file

2024-01-24 12:11 UTC, JoeGruffins commented
Moved sync to a new file sync.go, using the wallet logger, and removing the weird comment https://github.com/itswisdomagain/libwallet/compare/fc860e43f623be9509a7b41182bb9f584cbdc0f5..fa6a6a97b126fe92d0a6bc4aee9cd3a6c81d36e5

2024-01-25 03:43 UTC, JoeGruffins commented on asset/dcr/sync.go
> +	addr := &net.TCPAddr{IP: net.ParseIP("127.0.0.1"), Port: 0}
I just reverted. I don't know what this does.

2024-01-25 03:44 UTC, JoeGruffins commented
Reverted the ip address change https://github.com/itswisdomagain/libwallet/compare/f712df30b8537b989b7c33d872853241b0c91f8a..195af52e67f8e430e623aae7058d6037df9ac52b

2024-01-25 04:22 UTC, JoeGruffins commented on cgo/cgo.go
> +			log.Info("Sync completed.")
What happens if you close the backend before a log here?

2024-01-30 14:59 UTC, JoeGruffins commented
I just noticed that I don't find peers unless I set a persistent peer on testnet/mainnet. I guess I am doing something wrong? The wallet has a list of seeders?

2024-01-31 05:43 UTC, JoeGruffins commented
It looks like strings.Split makes a slice of len 1 for nothing so removing nothings https://github.com/itswisdomagain/libwallet/compare/195af52e67f8e430e623aae7058d6037df9ac52b..15646e3aadd829f4c504b8adcf7ed7b843e7cf93

2024-02-01 10:39 UTC, dreacot approved these changes
LGTM!

2024-02-02 17:33 UTC, itswisdomagain requested changes

2024-02-02 17:33 UTC, itswisdomagain commented on cgo/sync.go
> +	}
Requires walletsMtx lock. Can use `w, ok := loadedWallet(cName)`.

2024-02-02 17:33 UTC, itswisdomagain commented on cgo/sync.go
> +	for _, p := range splitPeers {
Would this work?
```suggestion
	var peers []string
	for _, p := range strings.Split(goString(cPeers), ",") {
```

2024-02-02 17:33 UTC, itswisdomagain commented on cgo/sync.go
> +	for _, p := range splitPeers {
Also need to trim `p`, I think, before checking if it's empty and before adding it to the slice.

2024-02-02 17:33 UTC, itswisdomagain commented on cgo/sync.go
> +	w, exists := wallets[name]
walletsMtx lock

2024-02-05 03:45 UTC, JoeGruffins commented on cgo/sync.go
> +	}
done

2024-02-05 03:46 UTC, JoeGruffins commented on cgo/sync.go
> +	w, exists := wallets[name]
doing w, ok := loadedWallet(cName).

2024-02-05 03:46 UTC, JoeGruffins commented on cgo/sync.go
> +	for _, p := range splitPeers {
Doing that

2024-02-05 03:46 UTC, JoeGruffins commented
Fix locks and strings https://github.com/itswisdomagain/libwallet/compare/15646e3aadd829f4c504b8adcf7ed7b843e7cf93..045e44d32fc9bce382a272348835d2eb9e991e11

2024-02-06 05:05 UTC, JoeGruffins commented on cgo/sync.go
> +		}
I couldnt remember if it's ok to assign to the thing you are iterating, but it is a value so probably fine anyway

2024-02-06 05:06 UTC, JoeGruffins commented on cgo/sync.go
> +		}
Fixed

2024-02-06 05:09 UTC, JoeGruffins commented
Using TrimSpace https://github.com/itswisdomagain/libwallet/compare/045e44d32fc9bce382a272348835d2eb9e991e11..8ff7395af5395f1eb9e9d806ba181d0848cefcb8

2024-02-13 11:07 UTC, merged