cgo: Add close wallet method.
itswisdomagain/libwallet pull request #9
Opened 2024-01-26 11:23 UTC by JoeGruffins

depends on #7 
closes #8

2024-01-26 11:24 UTC, JoeGruffins commented on cgo/cgo.go
> +	initiated  bool
Added initiate so we have a way to tell if logging and such was initiated rather than the wallets map. We can delete all the wallets and the state still be initiated now.

2024-01-26 11:25 UTC, JoeGruffins commented on cgo/sync.go
> +		return errCResponse("wallet with name %q does not exist", goString(cName))
I can also fix this in #7

2024-02-05 08:41 UTC, JoeGruffins commented
Sneaking this change in here if thats alright https://github.com/itswisdomagain/libwallet/compare/c4e62d7ca09b4cbfd3d6b14a9100bf6c2ac33ee0..d72e5fac4a7ee1a8b70649ee9a5733c2307d059b

2024-02-13 11:13 UTC, itswisdomagain requested changes

2024-02-13 11:13 UTC, itswisdomagain commented on cgo/cgo.go
> +	}
Should `initiated` be `initialized`? "not initiated" appears off to me.

2024-02-13 11:13 UTC, itswisdomagain commented on cgo/cgo.go
> +	walletsMtx.Lock()
Can this be in `walletloader.go`? Related `createWallet` and `loadWallet` methods are there...

2024-02-13 11:13 UTC, itswisdomagain commented on cgo/cgo.go
> +	return successCResponse("wallet %s shutdown", name)
%q, in case the name has multiple words or even funnily contains the text "shutdown"

2024-02-14 02:03 UTC, JoeGruffins commented on cgo/cgo.go
> +	}
Changed to initialized.

2024-02-14 02:17 UTC, JoeGruffins commented on cgo/cgo.go
> +	walletsMtx.Lock()
Moved it.

2024-02-14 02:18 UTC, JoeGruffins commented on cgo/cgo.go
> +	return successCResponse("wallet %s shutdown", name)
Changed to q.

2024-02-14 02:24 UTC, JoeGruffins commented
The three review points https://github.com/itswisdomagain/libwallet/compare/2ac711e1d5d2d26cff3eb62f458459dd5bbf3cbd..ef7255552f5ae0b73029a0bc679a2a7483f6a3bf

2024-02-16 07:02 UTC, itswisdomagain approved these changes

2024-02-16 07:02 UTC, merged